export const ActionType = {
  FETCHING_START: "FETCHING_START",
  FETCHING_SUCCESS: "FETCHING_SUCCESS",
  FETCHING_ERROR: "FETCHING_ERROR",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  DELETE_CART: "DELETE_CART",
  DELETE_WISHLIST: "DELETE_WISHLIST",
};
